/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as FoldersRouteImport } from './routes/folders'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoldersFolderIdRouteImport } from './routes/folders.$folderId'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignOutRouteImport } from './routes/auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthInitiateRouteImport } from './routes/auth/initiate'
import { Route as AuthGoogleRouteImport } from './routes/auth/google'
import { Route as AuthCliRouteImport } from './routes/auth/cli'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersRoute = FoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersFolderIdRoute = FoldersFolderIdRouteImport.update({
  id: '/$folderId',
  path: '/$folderId',
  getParentRoute: () => FoldersRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/auth/sign-out',
  path: '/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInitiateRoute = AuthInitiateRouteImport.update({
  id: '/auth/initiate',
  path: '/auth/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCliRoute = AuthCliRouteImport.update({
  id: '/auth/cli',
  path: '/auth/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/folders': typeof FoldersRouteWithChildren
  '/machines': typeof MachinesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/cli': typeof AuthCliRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/initiate': typeof AuthInitiateRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/folders': typeof FoldersRouteWithChildren
  '/machines': typeof MachinesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/cli': typeof AuthCliRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/initiate': typeof AuthInitiateRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/folders': typeof FoldersRouteWithChildren
  '/machines': typeof MachinesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/cli': typeof AuthCliRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/initiate': typeof AuthInitiateRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/folders'
    | '/machines'
    | '/auth/callback'
    | '/auth/cli'
    | '/auth/google'
    | '/auth/initiate'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/folders/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/folders'
    | '/machines'
    | '/auth/callback'
    | '/auth/cli'
    | '/auth/google'
    | '/auth/initiate'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/folders/$folderId'
  id:
    | '__root__'
    | '/'
    | '/folders'
    | '/machines'
    | '/auth/callback'
    | '/auth/cli'
    | '/auth/google'
    | '/auth/initiate'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/folders/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoldersRoute: typeof FoldersRouteWithChildren
  MachinesRoute: typeof MachinesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCliRoute: typeof AuthCliRoute
  AuthGoogleRoute: typeof AuthGoogleRoute
  AuthInitiateRoute: typeof AuthInitiateRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders': {
      id: '/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof FoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folderId': {
      id: '/folders/$folderId'
      path: '/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdRouteImport
      parentRoute: typeof FoldersRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-out': {
      id: '/auth/sign-out'
      path: '/auth/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/initiate': {
      id: '/auth/initiate'
      path: '/auth/initiate'
      fullPath: '/auth/initiate'
      preLoaderRoute: typeof AuthInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cli': {
      id: '/auth/cli'
      path: '/auth/cli'
      fullPath: '/auth/cli'
      preLoaderRoute: typeof AuthCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FoldersRouteChildren {
  FoldersFolderIdRoute: typeof FoldersFolderIdRoute
}

const FoldersRouteChildren: FoldersRouteChildren = {
  FoldersFolderIdRoute: FoldersFolderIdRoute,
}

const FoldersRouteWithChildren =
  FoldersRoute._addFileChildren(FoldersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoldersRoute: FoldersRouteWithChildren,
  MachinesRoute: MachinesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCliRoute: AuthCliRoute,
  AuthGoogleRoute: AuthGoogleRoute,
  AuthInitiateRoute: AuthInitiateRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
